/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 map_updated.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/map_updated.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.S1_B.geometry} material={nodes.S1_B.material} position={[9.988, 0.064, 1.063]} />
      <mesh geometry={nodes.S1_A_Right.geometry} material={nodes.S1_A_Right.material} position={[10.003, 0.064, 13.084]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.S1_C.geometry} material={nodes.S1_C.material} position={[-0.018, 0.064, -0.955]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.S1_D.geometry} material={nodes.S1_D.material} position={[-0.002, 0.064, 1.069]} />
      <mesh geometry={nodes.P2.geometry} material={nodes.P2.material} position={[-6.048, 0.064, -0.927]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.L2.geometry} material={nodes.L2.material} position={[-6.048, 0.064, -12.937]} />
      <mesh geometry={nodes.P1.geometry} material={nodes.P1.material} position={[16.005, 0.064, -0.945]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.L1.geometry} material={nodes.L1.material} position={[16.005, 0.064, -12.955]} />
      <mesh geometry={nodes.S2_D.geometry} material={nodes.S2_D.material} position={[-0.018, 0.078, -16.905]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.S2_A.geometry} material={nodes.S2_A.material} position={[9.988, 0.078, -14.887]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.S2_B.geometry} material={nodes.S2_B.material} position={[9.973, 0.078, -16.91]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.P3.geometry} material={nodes.P3.material} position={[16.018, 0.078, -14.914]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.P4.geometry} material={nodes.P4.material} position={[-6.035, 0.078, -14.896]} rotation={[0, 1.571, 0]} />
      <mesh geometry={nodes.start.geometry} material={nodes.start.material} position={[5.031, 0.062, 23.075]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.end.geometry} material={nodes.end.material} position={[5.02, 0.064, -29.004]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.S1_A_Left.geometry} material={nodes.S1_A_Left.material} position={[-0.001, 0.064, 13.084]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.S1_C_Right.geometry} material={nodes.S1_C_Right.material} position={[10.003, 0.064, -28.959]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.S2_C_Left.geometry} material={nodes.S2_C_Left.material} position={[-0.001, 0.064, -28.959]} rotation={[0, Math.PI / 2, 0]} />
    </group>
  )
}

useGLTF.preload('/map_updated.glb')
