/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 City.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function City(props) {
  const { nodes, materials } = useGLTF('/City.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[19.161, 0.1, 6.449]} scale={[0.969, 1.811, 0.969]}>
        <mesh geometry={nodes.Plane006_1.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Plane006_2.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Plane006_3.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Plane006_4.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Plane006_5.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Plane006_6.geometry} material={materials['Material.008']} />
      </group>
      <group position={[12.923, 0.1, -8.38]} scale={[0.969, 1.811, 0.969]}>
        <mesh geometry={nodes.Plane069.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Plane069_1.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Plane069_2.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Plane069_3.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Plane069_4.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Plane069_5.geometry} material={materials['Material.008']} />
      </group>
      <group position={[33.265, 0.1, 6.449]} rotation={[Math.PI, 0, Math.PI]} scale={[0.969, 1.811, 0.969]}>
        <mesh geometry={nodes.Plane070.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Plane070_1.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Plane070_2.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Plane070_3.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Plane070_4.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Plane070_5.geometry} material={materials['Material.008']} />
      </group>
      <group position={[39.134, 0.1, -8.38]} rotation={[Math.PI, 0, Math.PI]} scale={[0.969, 1.811, 0.969]}>
        <mesh geometry={nodes.Plane071.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Plane071_1.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Plane071_2.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Plane071_3.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Plane071_4.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Plane071_5.geometry} material={materials['Material.008']} />
      </group>
      <group position={[33.265, 0.1, -21.919]} rotation={[Math.PI, 0, Math.PI]} scale={[0.969, 1.811, 0.969]}>
        <mesh geometry={nodes.Plane072.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Plane072_1.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Plane072_2.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Plane072_3.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Plane072_4.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Plane072_5.geometry} material={materials['Material.008']} />
      </group>
      <group position={[22.718, 0.1, -8.201]}>
        {/* <mesh geometry={nodes.Plane002_1.geometry} material={materials.B_main_color} /> */}
        <mesh geometry={nodes.Plane002_1.geometry} material=<meshPhysicalMaterial
        
      
        roughness={0.5}
        metalness={0.2}
        
        emissive={"green"}
        emissiveIntensity={1}
      /> />
        <mesh geometry={nodes.Plane002_2.geometry} material={materials.B_Rooflight} />
        <mesh geometry={nodes.Plane002_3.geometry} material={materials.B_roof} />
        <mesh geometry={nodes.Plane002_4.geometry} material={materials.B_roofBoundary} />
        <mesh geometry={nodes.Plane002_5.geometry} material={materials.window} />
        <mesh geometry={nodes.Plane002_6.geometry} material={materials.B_door} />
      </group>
      <group position={[22.918, 0.1, -5.601]}>
        <mesh geometry={nodes.Plane003_1.geometry} material={materials['Material.050']} />
        <mesh geometry={nodes.Plane003_2.geometry} material={materials.BMain} />
        <mesh geometry={nodes.Plane003_3.geometry} material={materials['Material.052']} />
        <mesh geometry={nodes.Plane003_4.geometry} material={materials.window} />
        <mesh geometry={nodes.Plane003_5.geometry} material={materials.BEred} />
        <mesh geometry={nodes.Plane003_6.geometry} material={materials['Material.058']} />
        <mesh geometry={nodes.Plane003_7.geometry} material={materials.B_door} />
      </group>
      <group position={[22.954, 0.1, -5.601]}>
        <mesh geometry={nodes.Plane009_1.geometry} material={materials['Material.053']} />
        <mesh geometry={nodes.Plane009_2.geometry} material={materials['Material.054']} />
      </group>
      <group position={[15.534, 0.1, -27.212]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Plane044_1.geometry} material={materials.B_main_color} />
        <mesh geometry={nodes.Plane044_2.geometry} material={materials.B_Rooflight} />
        <mesh geometry={nodes.Plane044_3.geometry} material={materials.B_roof} />
        <mesh geometry={nodes.Plane044_4.geometry} material={materials.B_roofBoundary} />
        <mesh geometry={nodes.Plane044_5.geometry} material={materials.window} />
        <mesh geometry={nodes.Plane044_6.geometry} material={materials.B_door} />
      </group>
      <group position={[18.134, 0.1, -27.412]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Plane045.geometry} material={materials['Material.050']} />
        <mesh geometry={nodes.Plane045_1.geometry} material={materials.BMain} />
        <mesh geometry={nodes.Plane045_2.geometry} material={materials['Material.052']} />
        <mesh geometry={nodes.Plane045_3.geometry} material={materials.window} />
        <mesh geometry={nodes.Plane045_4.geometry} material={materials.BEred} />
        <mesh geometry={nodes.Plane045_5.geometry} material={materials['Material.058']} />
        <mesh geometry={nodes.Plane045_6.geometry} material={materials.B_door} />
      </group>
      <group position={[30.249, 0.1, -11.393]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Plane055.geometry} material={materials.B_main_color} />
        <mesh geometry={nodes.Plane055_1.geometry} material={materials.B_Rooflight} />
        <mesh geometry={nodes.Plane055_2.geometry} material={materials.B_roof} />
        <mesh geometry={nodes.Plane055_3.geometry} material={materials.B_roofBoundary} />
        <mesh geometry={nodes.Plane055_4.geometry} material={materials.window} />
        <mesh geometry={nodes.Plane055_5.geometry} material={materials.B_door} />
      </group>
      <group position={[32.849, 0.1, -11.593]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Plane056.geometry} material={materials['Material.050']} />
        <mesh geometry={nodes.Plane056_1.geometry} material={materials.BMain} />
        <mesh geometry={nodes.Plane056_2.geometry} material={materials['Material.052']} />
        <mesh geometry={nodes.Plane056_3.geometry} material={materials.window} />
        <mesh geometry={nodes.Plane056_4.geometry} material={materials.BEred} />
        <mesh geometry={nodes.Plane056_5.geometry} material={materials['Material.058']} />
        <mesh geometry={nodes.Plane056_6.geometry} material={materials.B_door} />
      </group>
      <group position={[32.849, 0.1, -11.629]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Plane057.geometry} material={materials['Material.053']} />
        <mesh geometry={nodes.Plane057_1.geometry} material={materials['Material.054']} />
      </group>
      <group position={[33.494, 0.1, -5.95]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Plane066.geometry} material={materials['Material.050']} />
        <mesh geometry={nodes.Plane066_1.geometry} material={materials.BMain} />
        <mesh geometry={nodes.Plane066_2.geometry} material={materials['Material.052']} />
        <mesh geometry={nodes.Plane066_3.geometry} material={materials.window} />
        <mesh geometry={nodes.Plane066_4.geometry} material={materials.BEred} />
        <mesh geometry={nodes.Plane066_5.geometry} material={materials['Material.058']} />
        <mesh geometry={nodes.Plane066_6.geometry} material={materials.B_door} />
      </group>
      
      <mesh geometry={nodes.Text.geometry} material={materials['Material.057']} position={[23.134, 2.4, -5.536]} rotation={[Math.PI / 2, 0, 0]} scale={0.448} />
      <group position={[20.718, 0.1, -6.201]} scale={[0.768, 0.96, 0.768]}>
        <mesh geometry={nodes.Plane011.geometry} material={materials.B_antenna} />
        <mesh geometry={nodes.Plane011_1.geometry} material={materials['B_eRed.001']} />
        <mesh geometry={nodes.Plane011_2.geometry} material={materials['B_main.001']} />
        <mesh geometry={nodes.Plane011_3.geometry} material={materials.window} />
      </group>
      <group position={[20.718, 0.1, -6.201]} scale={[0.768, 0.96, 0.768]}>
        <mesh geometry={nodes.Plane012.geometry} material={materials['B_main.001']} />
        <mesh geometry={nodes.Plane012_1.geometry} material={materials.window} />
        <mesh geometry={nodes.Plane012_2.geometry} material={materials.B_boundaryGlow} />
        <mesh geometry={nodes.Plane012_3.geometry} material={materials.B_door} />
      </group>
      <mesh geometry={nodes.Text001.geometry} material={materials['Material.069']} position={[20.734, 4.3, -5.426]} rotation={[Math.PI / 2, 0, 0]} scale={[1.254, 0.56, 1.254]} />
      
      <group position={[20.718, 0.1, -8.501]} scale={[0.84, 1.2, 1.2]}>
        <mesh geometry={nodes.Plane015.geometry} material={materials['Material.077']} />
        <mesh geometry={nodes.Plane015_1.geometry} material={materials.BigB_RoofGlow2} />
        <mesh geometry={nodes.Plane015_2.geometry} material={materials.BigB_RoofGlow} />
        <mesh geometry={nodes.Plane015_3.geometry} material={materials['Building Maiin']} />
        <mesh geometry={nodes.Plane015_4.geometry} material={materials.BigB_roof} />
        <mesh geometry={nodes.Plane015_5.geometry} material={materials.window} />
        <mesh geometry={nodes.Plane015_6.geometry} material={materials.BigB_boundaryGlow} />
      </group>
      <mesh geometry={nodes.Text002.geometry} material={materials['Material.080']} position={[20.718, 7.6, -7.326]} rotation={[Math.PI / 2, 0, 0]} scale={[1.49, 0.56, 1.49]} />
      <group position={[19.018, 0.1, -7.301]} scale={[0.768, 1.267, 0.768]}>
        <mesh geometry={nodes.Plane016.geometry} material={materials['Material.088']} />
        <mesh geometry={nodes.Plane016_1.geometry} material={materials.B_billboard2} />
        <mesh geometry={nodes.Plane016_2.geometry} material={materials.B_main} />
        <mesh geometry={nodes.Plane016_3.geometry} material={materials['window.002']} />
        <mesh geometry={nodes.Plane016_4.geometry} material={materials['Material.094']} />
        <mesh geometry={nodes.Plane016_5.geometry} material={materials.B_BillBoard} />
        <mesh geometry={nodes.Plane016_6.geometry} material={materials.window} />
        <mesh geometry={nodes.Plane016_7.geometry} material={materials.B_eRed} />
      </group>
      <mesh geometry={nodes.Text003.geometry} material={materials['Material.098']} position={[19.034, 4.072, -5.754]} rotation={[Math.PI / 2, 0, 0]} scale={[0.458, 0.327, 0.458]} />
      <mesh geometry={nodes.Text004.geometry} material={materials['Material.102']} position={[19.062, 5.4, -6.526]} rotation={[Math.PI / 2, 0, 0]} scale={[1.49, 0.56, 1.49]} />
      <group position={[21.674, 4.57, -8.701]} scale={[1, 3.25, 1]}>
        <mesh geometry={nodes.Plane019.geometry} material={materials['Material.106']} />
        <mesh geometry={nodes.Plane019_1.geometry} material={materials['Material.105']} />
      </group>
      <mesh geometry={nodes.Text005.geometry} material={materials['Material.057']} position={[18.199, 2.4, -27.628]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.448} />
      <group position={[17.534, 0.1, -25.212]} rotation={[0, Math.PI / 2, 0]} scale={[0.768, 0.96, 0.768]}>
        <mesh geometry={nodes.Plane046.geometry} material={materials.B_antenna} />
        <mesh geometry={nodes.Plane046_1.geometry} material={materials['B_eRed.001']} />
        <mesh geometry={nodes.Plane046_2.geometry} material={materials['B_main.001']} />
        <mesh geometry={nodes.Plane046_3.geometry} material={materials.window} />
      </group>
      <group position={[17.534, 0.1, -25.212]} rotation={[0, Math.PI / 2, 0]} scale={[0.768, 0.96, 0.768]}>
        <mesh geometry={nodes.Plane047.geometry} material={materials['B_main.001']} />
        <mesh geometry={nodes.Plane047_1.geometry} material={materials.window} />
        <mesh geometry={nodes.Plane047_2.geometry} material={materials.B_boundaryGlow} />
        <mesh geometry={nodes.Plane047_3.geometry} material={materials.B_door} />
      </group>
      <group position={[16.434, 0.1, -23.512]} rotation={[0, Math.PI / 2, 0]} scale={[0.768, 1.267, 0.768]}>
        <mesh geometry={nodes.Plane048.geometry} material={materials['Material.088']} />
        <mesh geometry={nodes.Plane048_1.geometry} material={materials.B_billboard2} />
        <mesh geometry={nodes.Plane048_2.geometry} material={materials.B_main} />
        <mesh geometry={nodes.Plane048_3.geometry} material={materials['window.002']} />
        <mesh geometry={nodes.Plane048_4.geometry} material={materials['Material.094']} />
        <mesh geometry={nodes.Plane048_5.geometry} material={materials.B_BillBoard} />
        <mesh geometry={nodes.Plane048_6.geometry} material={materials.window} />
        <mesh geometry={nodes.Plane048_7.geometry} material={materials.B_eRed} />
      </group>
      <group position={[32.249, 0.1, -9.393]} rotation={[0, Math.PI / 2, 0]} scale={[0.768, 0.96, 0.768]}>
        <mesh geometry={nodes.Plane058.geometry} material={materials.B_antenna} />
        <mesh geometry={nodes.Plane058_1.geometry} material={materials['B_eRed.001']} />
        <mesh geometry={nodes.Plane058_2.geometry} material={materials['B_main.001']} />
        <mesh geometry={nodes.Plane058_3.geometry} material={materials.window} />
      </group>
      <group position={[32.249, 0.1, -9.393]} rotation={[0, Math.PI / 2, 0]} scale={[0.768, 0.96, 0.768]}>
        <mesh geometry={nodes.Plane059.geometry} material={materials['B_main.001']} />
        <mesh geometry={nodes.Plane059_1.geometry} material={materials.window} />
        <mesh geometry={nodes.Plane059_2.geometry} material={materials.B_boundaryGlow} />
        <mesh geometry={nodes.Plane059_3.geometry} material={materials.B_door} />
      </group>
      
      <group position={[29.949, 0.1, -9.393]} rotation={[0, Math.PI / 2, 0]} scale={[0.84, 1.2, 1.2]}>
        <mesh geometry={nodes.Plane061.geometry} material={materials['Material.077']} />
        <mesh geometry={nodes.Plane061_1.geometry} material={materials.BigB_RoofGlow2} />
        <mesh geometry={nodes.Plane061_2.geometry} material={materials.BigB_RoofGlow} />
        <mesh geometry={nodes.Plane061_3.geometry} material={materials['Building Maiin']} />
        <mesh geometry={nodes.Plane061_4.geometry} material={materials.BigB_roof} />
        <mesh geometry={nodes.Plane061_5.geometry} material={materials.window} />
        <mesh geometry={nodes.Plane061_6.geometry} material={materials.BigB_boundaryGlow} />
      </group>
      <group position={[31.149, 0.1, -7.693]} rotation={[0, Math.PI / 2, 0]} scale={[0.768, 1.267, 0.768]}>
        <mesh geometry={nodes.Plane062.geometry} material={materials['Material.088']} />
        <mesh geometry={nodes.Plane062_1.geometry} material={materials.B_billboard2} />
        <mesh geometry={nodes.Plane062_2.geometry} material={materials.B_main} />
        <mesh geometry={nodes.Plane062_3.geometry} material={materials['window.002']} />
        <mesh geometry={nodes.Plane062_4.geometry} material={materials['Material.094']} />
        <mesh geometry={nodes.Plane062_5.geometry} material={materials.B_BillBoard} />
        <mesh geometry={nodes.Plane062_6.geometry} material={materials.window} />
        <mesh geometry={nodes.Plane062_7.geometry} material={materials.B_eRed} />
      </group>
      <group position={[29.749, 4.57, -10.348]} rotation={[0, Math.PI / 2, 0]} scale={[1, 3.25, 1]}>
        <mesh geometry={nodes.Plane063.geometry} material={materials['Material.106']} />
        <mesh geometry={nodes.Plane063_1.geometry} material={materials['Material.105']} />
      </group>
      <group position={[31.149, 0.1, -4.777]} rotation={[0, Math.PI / 2, 0]} scale={[0.768, 1.267, 0.768]}>
        <mesh geometry={nodes.Plane065.geometry} material={materials['Material.088']} />
        <mesh geometry={nodes.Plane065_1.geometry} material={materials.B_billboard2} />
        <mesh geometry={nodes.Plane065_2.geometry} material={materials.B_main} />
        <mesh geometry={nodes.Plane065_3.geometry} material={materials['window.002']} />
        <mesh geometry={nodes.Plane065_4.geometry} material={materials['Material.094']} />
        <mesh geometry={nodes.Plane065_5.geometry} material={materials.B_BillBoard} />
        <mesh geometry={nodes.Plane065_6.geometry} material={materials.window} />
        <mesh geometry={nodes.Plane065_7.geometry} material={materials.B_eRed} />
      </group>
      <group position={[15.416, 0.1, -25.235]} rotation={[0, Math.PI / 2, 0]} scale={[0.77, 1.101, 1.101]}>
        <mesh geometry={nodes.Plane067.geometry} material={materials['Material.077']} />
        <mesh geometry={nodes.Plane067_1.geometry} material={materials.BigB_RoofGlow2} />
        <mesh geometry={nodes.Plane067_2.geometry} material={materials.BigB_RoofGlow} />
        <mesh geometry={nodes.Plane067_3.geometry} material={materials['Building Maiin']} />
        <mesh geometry={nodes.Plane067_4.geometry} material={materials.BigB_roof} />
        <mesh geometry={nodes.Plane067_5.geometry} material={materials.window} />
        <mesh geometry={nodes.Plane067_6.geometry} material={materials.BigB_boundaryGlow} />
      </group>
    </group>
  )
}

useGLTF.preload('/City.glb')
