// tutorial https://redux.js.org/tutorials/quick-start

import { createSlice } from '@reduxjs/toolkit'

// Create a new slice of the Redux store with the name 'state'
// and an initial state object containing three properties:
// value_of_clr_button, end_value, and start_value.
// Also define several reducer functions that can be used to update
// the state in response to different actions.
export const StateSlice = createSlice({
  name: 'state',
  initialState: {
    value_of_clr_button: false,
    end_value : '',
    start_value : '',
  },
  reducers: {
    // A reducer function that sets the value_of_clr_button property
    // of the state object to the value of the payload property of the
    // action object passed to it.
    clear_path: (state, action) => {
      state.value_of_clr_button = action.payload;
    },
    // A reducer function that sets the start_value property
    // of the state object to the value of the payload property of the
    // action object passed to it.
    getStart: (state, action)=>{
      state.start_value = action.payload;
    },
    // A reducer function that sets the end_value property
    // of the state object to the value of the payload property of the
    // action object passed to it.
    getEnd: (state, action)=> {
      state.end_value = action.payload;
    },
    // A reducer function that decrements the value property
    // of the state object by 1.
    decrement: (state) => {
      state.value -= 1
    },
    // A reducer function that increments the value property
    // of the state object by the value of the payload property of the
    // action object passed to it.
    incrementByAmount: (state, action) => {
      state.value += action.payload
    },
  },
})

// Export the action creator functions generated by the createSlice function
// for each of the reducer functions defined above.
export const { clear_path, decrement, incrementByAmount,getEnd, getStart } = StateSlice.actions

// Export the reducer function generated by the createSlice function
// for the 'state' slice of the Redux store.
export default StateSlice.reducer
