/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 AnimatedMan.glb
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations} from '@react-three/drei'

export function HoverBoard(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/AnimatedMan.glb')
  const { actions ,animNames} = useAnimations(animations, group)
  console.log(animNames)

  useEffect(()=>{
    actions['Armature.001|mixamo.com|Layer0'].fadeIn(0.5).play();
  },[])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
      
        <group name="Sketchfab_model" position={[0, -0.063, 0.097]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.129}>
          <group name="Root" position={[0, 0.224, -0.56]}>
            <group name="Circle004" position={[-1.578, 0.019, 0.033]} scale={1.257} />
            <group name="Circle005" position={[2.45, 0.019, 0.033]} scale={1.402} />
            <group name="hover_board" position={[0.576, 0, 1.83]} rotation={[-Math.PI, 0, -Math.PI]}>
              <mesh name="hover_board_0" geometry={nodes.hover_board_0.geometry} material={materials['Material.001']} />
              <mesh name="hover_board_1" geometry={nodes.hover_board_1.geometry} material={materials['Material.005']} />
              <mesh name="hover_board_2" geometry={nodes.hover_board_2.geometry} material={materials['Material.003']} />
              <mesh name="hover_board_3" geometry={nodes.hover_board_3.geometry} material={materials['Material.007']} />
              <mesh name="hover_board_4" geometry={nodes.hover_board_4.geometry} material={materials['Material.002']} />
              <mesh name="hover_board_5" geometry={nodes.hover_board_5.geometry} material={materials['Material.004']} />
              <mesh name="hover_board_6" geometry={nodes.hover_board_6.geometry} material={materials['Material.006']} />
              <mesh name="hover_board_7" geometry={nodes.hover_board_7.geometry} material={materials['Material.015']} />
            </group>
            <group name="Lamp" position={[-3.501, 1.005, -4.074]} rotation={[-2.873, -0.602, -1.21]}>
              <group name="Lamp001" />
            </group>
          </group>
        </group>
        <group name="Armature001" position={[0, 0, 0.006]}>
          <primitive object={nodes.Hips} />
          <skinnedMesh name="Wolf3D_Body001" geometry={nodes.Wolf3D_Body001.geometry} material={materials.Wolf3D_Body} skeleton={nodes.Wolf3D_Body001.skeleton} />
          <skinnedMesh name="Wolf3D_Headwear001" geometry={nodes.Wolf3D_Headwear001.geometry} material={materials.Wolf3D_Headwear} skeleton={nodes.Wolf3D_Headwear001.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Bottom001" geometry={nodes.Wolf3D_Outfit_Bottom001.geometry} material={materials.Wolf3D_Outfit_Bottom} skeleton={nodes.Wolf3D_Outfit_Bottom001.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Footwear001" geometry={nodes.Wolf3D_Outfit_Footwear001.geometry} material={materials.Wolf3D_Outfit_Footwear} skeleton={nodes.Wolf3D_Outfit_Footwear001.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Top001" geometry={nodes.Wolf3D_Outfit_Top001.geometry} material={materials.Wolf3D_Outfit_Top} skeleton={nodes.Wolf3D_Outfit_Top001.skeleton} />
          <skinnedMesh name="EyeLeft001" geometry={nodes.EyeLeft001.geometry} material={materials['Wolf3D_Eye.001']} skeleton={nodes.EyeLeft001.skeleton} morphTargetDictionary={nodes.EyeLeft001.morphTargetDictionary} morphTargetInfluences={nodes.EyeLeft001.morphTargetInfluences} />
          <skinnedMesh name="EyeRight001" geometry={nodes.EyeRight001.geometry} material={materials['Wolf3D_Eye.001']} skeleton={nodes.EyeRight001.skeleton} morphTargetDictionary={nodes.EyeRight001.morphTargetDictionary} morphTargetInfluences={nodes.EyeRight001.morphTargetInfluences} />
          <skinnedMesh name="Wolf3D_Head001" geometry={nodes.Wolf3D_Head001.geometry} material={materials.Wolf3D_Skin} skeleton={nodes.Wolf3D_Head001.skeleton} morphTargetDictionary={nodes.Wolf3D_Head001.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Head001.morphTargetInfluences} />
          <skinnedMesh name="Wolf3D_Teeth001" geometry={nodes.Wolf3D_Teeth001.geometry} material={materials['Wolf3D_Teeth.001']} skeleton={nodes.Wolf3D_Teeth001.skeleton} morphTargetDictionary={nodes.Wolf3D_Teeth001.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Teeth001.morphTargetInfluences} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/AnimatedMan.glb')
