/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 Hovership.glb
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Hovership(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Hovership.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(()=>{
    actions['hoverAnim'].fadeIn(0.5).play();
  },[])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Cube003" position={[0, 1.501, 0]}>
          <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials.Mat0} />
          <mesh name="Cube005_1" geometry={nodes.Cube005_1.geometry} material={materials.Mat1} />
          <mesh name="Cube005_2" geometry={nodes.Cube005_2.geometry} material={materials.Mat2} />
          <mesh name="Cube005_3" geometry={nodes.Cube005_3.geometry} material={materials.Window_Frame} />
          <mesh name="Cube005_4" geometry={nodes.Cube005_4.geometry} material={materials.Mat4} />
          <mesh name="Cube005_5" geometry={nodes.Cube005_5.geometry} material={materials.Mat3} />
          <mesh name="Cube005_6" geometry={nodes.Cube005_6.geometry} material={materials.Window} />
        </group>
        <group name="Cube" scale={[3.99, 0.055, 3.99]}>
          <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials.Mat2} />
          <mesh name="Cube001_1" geometry={nodes.Cube001_1.geometry} material={materials.Mat1} />
          <mesh name="Cube001_2" geometry={nodes.Cube001_2.geometry} material={materials.Mat4} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Hovership.glb')
